// Builds .env.production.local from what you paste/drop into firebase-setup/:
//   - the firebaseConfig block from Firebase console → Project settings → Your apps
//     (paste it into firebase-setup/paste-firebase-config-here.txt)
//   - the service account key file from Project settings → Service accounts
//     (move the downloaded .json file into firebase-setup/)
//
//   npm run env:prod
//
// Also writes firebase-setup/vercel-env.txt — paste its whole contents into
// Vercel → Settings → Environment Variables to add every variable at once.
// firebase-setup/ and the env files are git-ignored.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const dir = "firebase-setup";
const envFile = ".env.production.local";

if (!existsSync(dir)) {
  console.error(`No ${dir}/ folder. Create it and add your Firebase config + key file first.`);
  process.exit(1);
}

let config = null;
let account = null;
for (const name of readdirSync(dir)) {
  if (name === "vercel-env.txt" || name === "README.txt") continue;
  const text = readFileSync(path.join(dir, name), "utf8");
  if (text.includes("private_key")) {
    try {
      account = JSON.parse(text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1));
    } catch {
      console.error(`${name} looks like a key file but isn't valid JSON — download it again.`);
      process.exit(1);
    }
  } else if (text.includes("apiKey")) {
    config = {};
    for (const [, key, value] of text.matchAll(/(\w+)\s*:\s*["']([^"']+)["']/g)) config[key] = value;
  }
}

const missing = [];
if (!config?.apiKey) missing.push(`the firebaseConfig block (paste it into ${dir}/paste-firebase-config-here.txt)`);
if (!account?.private_key) missing.push(`the service account key file (move the downloaded .json into ${dir}/)`);
if (missing.length) {
  console.error("Still needed:\n  - " + missing.join("\n  - "));
  process.exit(1);
}
if (account.project_id !== config.projectId) {
  console.error(`The key file is for "${account.project_id}" but the config is for "${config.projectId}". Use files from the same project.`);
  process.exit(1);
}

// Keep any email (SMTP) settings already filled in.
const existing = {};
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, "utf8").split(/\r?\n/)) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m) existing[m[1]] = m[2];
  }
}

const privateKey = account.private_key.replace(/\n/g, "\\n");
const vars = {
  NEXT_PUBLIC_SITE_URL: "https://www.clearsitestudios.co.za",
  NEXT_PUBLIC_FIREBASE_API_KEY: config.apiKey,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: config.authDomain ?? `${config.projectId}.firebaseapp.com`,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: config.projectId,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: config.storageBucket ?? "",
  NEXT_PUBLIC_FIREBASE_APP_ID: config.appId ?? "",
  NEXT_PUBLIC_USE_EMULATORS: "false",
  FIREBASE_PROJECT_ID: account.project_id,
  FIREBASE_CLIENT_EMAIL: account.client_email,
  FIREBASE_PRIVATE_KEY: `"${privateKey}"`,
  SMTP_HOST: existing.SMTP_HOST ?? "",
  SMTP_PORT: existing.SMTP_PORT || "587",
  SMTP_USER: existing.SMTP_USER ?? "",
  SMTP_PASSWORD: existing.SMTP_PASSWORD ?? "",
  NOTIFY_EMAIL: existing.NOTIFY_EMAIL || "clearsitestudios@outlook.com",
  // Push notification keys — kept as they are, since new keys would switch off every phone's notifications.
  NEXT_PUBLIC_VAPID_PUBLIC_KEY: existing.NEXT_PUBLIC_VAPID_PUBLIC_KEY ?? "",
  VAPID_PRIVATE_KEY: existing.VAPID_PRIVATE_KEY ?? "",
  VAPID_SUBJECT: existing.VAPID_SUBJECT || "mailto:clearsitestudios@outlook.com",
};

const body = Object.entries(vars).map(([k, v]) => `${k}=${v}`).join("\n");
writeFileSync(
  envFile,
  `# Generated by npm run env:prod — git-ignored, never commit or share.\n# SMTP_* (email alerts) can be filled in by hand; re-running keeps them.\n${body}\n`,
);
// Vercel: only variables that have a value (it rejects empty ones).
writeFileSync(
  path.join(dir, "vercel-env.txt"),
  Object.entries(vars)
    .filter(([, v]) => v !== "" && v !== '""')
    .map(([k, v]) => `${k}=${v}`)
    .join("\n") + "\n",
);

console.log(`Wrote ${envFile} and ${dir}/vercel-env.txt for project "${config.projectId}".`);
const smtpMissing = ["SMTP_HOST", "SMTP_USER", "SMTP_PASSWORD"].filter((k) => !vars[k]);
if (smtpMissing.length) {
  console.log(`Email alerts: ${smtpMissing.join(", ")} still empty — fill them in ${envFile} (or in Vercel) if you want emails.`);
}
if (!vars.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET) console.log("No storageBucket in the config — that's fine if you're skipping Firebase Storage.");
